spring:
  mail:
    password: phdkyzggyjjjjggg
    host: smtp.qq.com
    username: chikaho@foxmail.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dd_net?serverTimezone=Asia/Shanghai&useSSL=true&characterEncoding=UTF-8
    username: root
    password: 123456
  mvc:
    static-path-pattern: /static/**
  messages:
    basename: i18n.index
  #  热部署
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  devtools:
    restart:
      additional-paths: src/main/java
  freemarker:
    cache: false
mybatis:
  type-aliases-package: net.dd.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown
qiniu:
  accessKey: ciIKJAtiHkSeEAm_Ci3MjuXvWPN2gZB_mY4wsOSK
  secretKey: 5LIinEdTfH3eLf_HlAhfSYUC19leeBSScdf2C-r5
  # 对象储存
  bucket: ddnetdemo # 空间名称
  zone: huanan # 存储区域
  domain: qt1bcqgbl.hn-bkt.clouddn.com # 访问域名
##jwt配置
audience:
  # 代表这个JWT的接收对象,存入audience
  clientId: 098f6bcd4621d373cade4e832627b4f6
  # 密钥, 经过Base64加密, 可自行替换
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # JWT的签发主体，存入issuer
  name: restapiuser
  # 过期时间，时间戳
  expiresSecond: 172800
  Authorization: Bearer <token>